'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://systemagmbh.com/milling-automation/r1/", ClrNamespace:="systemagmbh.com.millingautomation.r1")> 


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", ConfigurationName:="MillingIntegrationServiceR1_4")>  _
Public Interface MillingIntegrationServiceR1_4
    
    'CODEGEN: Generating message contract since the operation completeBoard is neither RPC nor document wrapped.
    <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(systemagmbh.com.millingautomation.r1.AutomationException), Action:="", Name:="AutomationException"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(genericREQ))>  _
    Function completeBoard(ByVal request As completeBoardRequest) As completeBoardResponse1
    
    'CODEGEN: Generating message contract since the operation completePCB is neither RPC nor document wrapped.
    <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(systemagmbh.com.millingautomation.r1.AutomationException), Action:="", Name:="AutomationException"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(genericREQ))>  _
    Function completePCB(ByVal request As completePCBRequest) As completePCBResponse1
    
    'CODEGEN: Generating message contract since the operation startBoard is neither RPC nor document wrapped.
    <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(systemagmbh.com.millingautomation.r1.AutomationException), Action:="", Name:="AutomationException"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(genericREQ))>  _
    Function startBoard(ByVal request As startBoardRequest) As startBoardResponse1
    
    'CODEGEN: Generating message contract since the operation validateMilling is neither RPC nor document wrapped.
    <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(systemagmbh.com.millingautomation.r1.AutomationException), Action:="", Name:="AutomationException"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(genericREQ))>  _
    Function validateMilling(ByVal request As validateMillingRequest) As validateMillingResponse1
    
    'CODEGEN: Generating message contract since the operation changeResourceState is neither RPC nor document wrapped.
    <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(systemagmbh.com.millingautomation.r1.AutomationException), Action:="", Name:="AutomationException"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(genericREQ))>  _
    Function changeResourceState(ByVal request As changeResourceStateRequest) As changeResourceStateResponse1
End Interface

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class completeBoard
    
    Private completeBoardRequestField As operSFCREQ
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property CompleteBoardRequest() As operSFCREQ
        Get
            Return Me.completeBoardRequestField
        End Get
        Set
            Me.completeBoardRequestField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(validateMillingREQ)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(startBoardREQ)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(completePCBREQ)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class operSFCREQ
    Inherits genericREQ
    
    Private operationField As String
    
    Private sfcField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property operation() As String
        Get
            Return Me.operationField
        End Get
        Set
            Me.operationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property sfc() As String
        Get
            Return Me.sfcField
        End Get
        Set
            Me.sfcField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(changeResourceStateREQ)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(operSFCREQ)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(validateMillingREQ)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(startBoardREQ)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(completePCBREQ)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class genericREQ
    
    Private softwareRevisionField As String
    
    Private timeStampField As Date
    
    Private resourceIdField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property softwareRevision() As String
        Get
            Return Me.softwareRevisionField
        End Get
        Set
            Me.softwareRevisionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property timeStamp() As Date
        Get
            Return Me.timeStampField
        End Get
        Set
            Me.timeStampField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
    Public Property resourceId() As String
        Get
            Return Me.resourceIdField
        End Get
        Set
            Me.resourceIdField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class changeResourceStateResponse
    
    Private returnField As genericRSP
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property [return]() As genericRSP
        Get
            Return Me.returnField
        End Get
        Set
            Me.returnField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(validateMillingRSP)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class genericRSP
    
    Private resultCodeField As Integer
    
    Private resultTextField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property resultCode() As Integer
        Get
            Return Me.resultCodeField
        End Get
        Set
            Me.resultCodeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property resultText() As String
        Get
            Return Me.resultTextField
        End Get
        Set
            Me.resultTextField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class validateMillingRSP
    Inherits genericRSP
    
    Private laneField As String
    
    Private recipeField As String
    
    Private sfcField As String
    
    Private singleBoardsField() As SingleBoard
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property lane() As String
        Get
            Return Me.laneField
        End Get
        Set
            Me.laneField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property recipe() As String
        Get
            Return Me.recipeField
        End Get
        Set
            Me.recipeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
    Public Property sfc() As String
        Get
            Return Me.sfcField
        End Get
        Set
            Me.sfcField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("singleBoards", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
    Public Property singleBoards() As SingleBoard()
        Get
            Return Me.singleBoardsField
        End Get
        Set
            Me.singleBoardsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class SingleBoard
    
    Private locationField As String
    
    Private stateField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property location() As String
        Get
            Return Me.locationField
        End Get
        Set
            Me.locationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property state() As String
        Get
            Return Me.stateField
        End Get
        Set
            Me.stateField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class changeResourceState
    
    Private changeResourceStateRequestField As changeResourceStateREQ
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property changeResourceStateRequest() As changeResourceStateREQ
        Get
            Return Me.changeResourceStateRequestField
        End Get
        Set
            Me.changeResourceStateRequestField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class changeResourceStateREQ
    Inherits genericREQ
    
    Private newStateField As String
    
    Private rcCommentField As String
    
    Private reasonCodeField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property newState() As String
        Get
            Return Me.newStateField
        End Get
        Set
            Me.newStateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property rcComment() As String
        Get
            Return Me.rcCommentField
        End Get
        Set
            Me.rcCommentField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
    Public Property reasonCode() As String
        Get
            Return Me.reasonCodeField
        End Get
        Set
            Me.reasonCodeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class validateMillingResponse
    
    Private returnField As validateMillingRSP
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property [return]() As validateMillingRSP
        Get
            Return Me.returnField
        End Get
        Set
            Me.returnField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class validateMilling
    
    Private validateMillingRequestField As validateMillingREQ
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property validateMillingRequest() As validateMillingREQ
        Get
            Return Me.validateMillingRequestField
        End Get
        Set
            Me.validateMillingRequestField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class validateMillingREQ
    Inherits operSFCREQ
    
    Private amountOfBoardsField As String
    
    Private laneField As String
    
    Private recipeField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property amountOfBoards() As String
        Get
            Return Me.amountOfBoardsField
        End Get
        Set
            Me.amountOfBoardsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property lane() As String
        Get
            Return Me.laneField
        End Get
        Set
            Me.laneField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
    Public Property recipe() As String
        Get
            Return Me.recipeField
        End Get
        Set
            Me.recipeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class startBoardResponse
    
    Private returnField As genericRSP
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property [return]() As genericRSP
        Get
            Return Me.returnField
        End Get
        Set
            Me.returnField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class startBoard
    
    Private startBoardRequestField As startBoardREQ
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property startBoardRequest() As startBoardREQ
        Get
            Return Me.startBoardRequestField
        End Get
        Set
            Me.startBoardRequestField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class startBoardREQ
    Inherits operSFCREQ
    
    Private recipeField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property recipe() As String
        Get
            Return Me.recipeField
        End Get
        Set
            Me.recipeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class completePCBResponse
    
    Private returnField As genericRSP
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property [return]() As genericRSP
        Get
            Return Me.returnField
        End Get
        Set
            Me.returnField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class completePCB
    
    Private completePCBRequestField As completePCBREQ
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property completePCBRequest() As completePCBREQ
        Get
            Return Me.completePCBRequestField
        End Get
        Set
            Me.completePCBRequestField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class completePCBREQ
    Inherits operSFCREQ
    
    Private locationField As String
    
    Private stateField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property location() As String
        Get
            Return Me.locationField
        End Get
        Set
            Me.locationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property state() As String
        Get
            Return Me.stateField
        End Get
        Set
            Me.stateField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class completeBoardResponse
    
    Private returnField As genericRSP
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property [return]() As genericRSP
        Get
            Return Me.returnField
        End Get
        Set
            Me.returnField = value
        End Set
    End Property
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class completeBoardRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public completeBoard As completeBoard
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal completeBoard As completeBoard)
        MyBase.New
        Me.completeBoard = completeBoard
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class completeBoardResponse1
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public completeBoardResponse As completeBoardResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal completeBoardResponse As completeBoardResponse)
        MyBase.New
        Me.completeBoardResponse = completeBoardResponse
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class completePCBRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public completePCB As completePCB
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal completePCB As completePCB)
        MyBase.New
        Me.completePCB = completePCB
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class completePCBResponse1
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public completePCBResponse As completePCBResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal completePCBResponse As completePCBResponse)
        MyBase.New
        Me.completePCBResponse = completePCBResponse
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class startBoardRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public startBoard As startBoard
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal startBoard As startBoard)
        MyBase.New
        Me.startBoard = startBoard
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class startBoardResponse1
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public startBoardResponse As startBoardResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal startBoardResponse As startBoardResponse)
        MyBase.New
        Me.startBoardResponse = startBoardResponse
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class validateMillingRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public validateMilling As validateMilling
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal validateMilling As validateMilling)
        MyBase.New
        Me.validateMilling = validateMilling
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class validateMillingResponse1
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public validateMillingResponse As validateMillingResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal validateMillingResponse As validateMillingResponse)
        MyBase.New
        Me.validateMillingResponse = validateMillingResponse
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class changeResourceStateRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public changeResourceState As changeResourceState
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal changeResourceState As changeResourceState)
        MyBase.New
        Me.changeResourceState = changeResourceState
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class changeResourceStateResponse1
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public changeResourceStateResponse As changeResourceStateResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal changeResourceStateResponse As changeResourceStateResponse)
        MyBase.New
        Me.changeResourceStateResponse = changeResourceStateResponse
    End Sub
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Public Interface MillingIntegrationServiceR1_4Channel
    Inherits MillingIntegrationServiceR1_4, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Partial Public Class MillingIntegrationServiceR1_4Client
    Inherits System.ServiceModel.ClientBase(Of MillingIntegrationServiceR1_4)
    Implements MillingIntegrationServiceR1_4
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function MillingIntegrationServiceR1_4_completeBoard(ByVal request As completeBoardRequest) As completeBoardResponse1 Implements MillingIntegrationServiceR1_4.completeBoard
        Return MyBase.Channel.completeBoard(request)
    End Function
    
    Public Function completeBoard(ByVal completeBoard1 As completeBoard) As completeBoardResponse
        Dim inValue As completeBoardRequest = New completeBoardRequest()
        inValue.completeBoard = completeBoard1
        Dim retVal As completeBoardResponse1 = CType(Me,MillingIntegrationServiceR1_4).completeBoard(inValue)
        Return retVal.completeBoardResponse
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function MillingIntegrationServiceR1_4_completePCB(ByVal request As completePCBRequest) As completePCBResponse1 Implements MillingIntegrationServiceR1_4.completePCB
        Return MyBase.Channel.completePCB(request)
    End Function
    
    Public Function completePCB(ByVal completePCB1 As completePCB) As completePCBResponse
        Dim inValue As completePCBRequest = New completePCBRequest()
        inValue.completePCB = completePCB1
        Dim retVal As completePCBResponse1 = CType(Me,MillingIntegrationServiceR1_4).completePCB(inValue)
        Return retVal.completePCBResponse
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function MillingIntegrationServiceR1_4_startBoard(ByVal request As startBoardRequest) As startBoardResponse1 Implements MillingIntegrationServiceR1_4.startBoard
        Return MyBase.Channel.startBoard(request)
    End Function
    
    Public Function startBoard(ByVal startBoard1 As startBoard) As startBoardResponse
        Dim inValue As startBoardRequest = New startBoardRequest()
        inValue.startBoard = startBoard1
        Dim retVal As startBoardResponse1 = CType(Me,MillingIntegrationServiceR1_4).startBoard(inValue)
        Return retVal.startBoardResponse
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function MillingIntegrationServiceR1_4_validateMilling(ByVal request As validateMillingRequest) As validateMillingResponse1 Implements MillingIntegrationServiceR1_4.validateMilling
        Return MyBase.Channel.validateMilling(request)
    End Function
    
    Public Function validateMilling(ByVal validateMilling1 As validateMilling) As validateMillingResponse
        Dim inValue As validateMillingRequest = New validateMillingRequest()
        inValue.validateMilling = validateMilling1
        Dim retVal As validateMillingResponse1 = CType(Me,MillingIntegrationServiceR1_4).validateMilling(inValue)
        Return retVal.validateMillingResponse
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function MillingIntegrationServiceR1_4_changeResourceState(ByVal request As changeResourceStateRequest) As changeResourceStateResponse1 Implements MillingIntegrationServiceR1_4.changeResourceState
        Return MyBase.Channel.changeResourceState(request)
    End Function
    
    Public Function changeResourceState(ByVal changeResourceState1 As changeResourceState) As changeResourceStateResponse
        Dim inValue As changeResourceStateRequest = New changeResourceStateRequest()
        inValue.changeResourceState = changeResourceState1
        Dim retVal As changeResourceStateResponse1 = CType(Me,MillingIntegrationServiceR1_4).changeResourceState(inValue)
        Return retVal.changeResourceStateResponse
    End Function
End Class

Namespace systemagmbh.com.millingautomation.r1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema"),  _
     System.Xml.Serialization.XmlRootAttribute(IsNullable:=false)>  _
    Partial Public Class AutomationException
        Inherits Object
        Implements System.Xml.Serialization.IXmlSerializable
        
        Private nodesField() As System.Xml.XmlNode
        
        Private Shared typeName As System.Xml.XmlQualifiedName = New System.Xml.XmlQualifiedName("AutomationException", "http://systemagmbh.com/milling-automation/r1/")
        
        Public Property Nodes() As System.Xml.XmlNode()
            Get
                Return Me.nodesField
            End Get
            Set
                Me.nodesField = value
            End Set
        End Property
        
        Public Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements System.Xml.Serialization.IXmlSerializable.ReadXml
            Me.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader)
        End Sub
        
        Public Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements System.Xml.Serialization.IXmlSerializable.WriteXml
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, Me.Nodes)
        End Sub
        
        Public Function GetSchema() As System.Xml.Schema.XmlSchema Implements System.Xml.Serialization.IXmlSerializable.GetSchema
            Return Nothing
        End Function
        
        Public Shared Function ExportSchema(ByVal schemas As System.Xml.Schema.XmlSchemaSet) As System.Xml.XmlQualifiedName
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName)
            Return typeName
        End Function
    End Class
End Namespace
