'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://systemagmbh.com/milling-automation/r1/", ClrNamespace:="systemagmbh.com.millingautomation.r1")> 


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", ConfigurationName:="MillingIntegrationServiceR1_5")>  _
Public Interface MillingIntegrationServiceR1_5
    
    'CODEGEN: Generating message contract since the operation completeBoard is neither RPC nor document wrapped.
    <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(systemagmbh.com.millingautomation.r1.AutomationException), Action:="", Name:="AutomationException"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(BasicSplitResponse)),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(genericREQ))>  _
    Function completeBoard(ByVal request As completeBoardRequest) As completeBoardResponse1
    
    'CODEGEN: Generating message contract since the operation completePCB is neither RPC nor document wrapped.
    <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(systemagmbh.com.millingautomation.r1.AutomationException), Action:="", Name:="AutomationException"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(BasicSplitResponse)),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(genericREQ))>  _
    Function completePCB(ByVal request As completePCBRequest) As completePCBResponse1
    
    'CODEGEN: Generating message contract since the operation startBoard is neither RPC nor document wrapped.
    <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(systemagmbh.com.millingautomation.r1.AutomationException), Action:="", Name:="AutomationException"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(BasicSplitResponse)),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(genericREQ))>  _
    Function startBoard(ByVal request As startBoardRequest) As startBoardResponse1
    
    'CODEGEN: Generating message contract since the operation validateMilling is neither RPC nor document wrapped.
    <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(systemagmbh.com.millingautomation.r1.AutomationException), Action:="", Name:="AutomationException"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(BasicSplitResponse)),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(genericREQ))>  _
    Function validateMilling(ByVal request As validateMillingRequest) As validateMillingResponse1
    
    'CODEGEN: Generating message contract since the operation changeResourceState is neither RPC nor document wrapped.
    <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(systemagmbh.com.millingautomation.r1.AutomationException), Action:="", Name:="AutomationException"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(BasicSplitResponse)),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(genericREQ))>  _
    Function changeResourceState(ByVal request As changeResourceStateRequest) As changeResourceStateResponse1
    
    'CODEGEN: Generating message contract since the operation serializeMilling is neither RPC nor document wrapped.
    <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(systemagmbh.com.millingautomation.r1.ECoBaseMeClient61Exception), Action:="", Name:="ECoBaseMeClient61Exception"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(BasicSplitResponse)),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(genericREQ))>  _
    Function serializeMilling(ByVal request As serializeMillingRequest) As serializeMillingResponse
    
    'CODEGEN: Generating message contract since the operation autoComplete is neither RPC nor document wrapped.
    <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
     System.ServiceModel.FaultContractAttribute(GetType(systemagmbh.com.millingautomation.r1.AutomationException), Action:="", Name:="AutomationException"),  _
     System.ServiceModel.FaultContractAttribute(GetType(systemagmbh.com.millingautomation.r1.ECoBaseMeClient61Exception), Action:="", Name:="ECoBaseMeClient61Exception"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(BasicSplitResponse)),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(genericREQ))>  _
    Function autoComplete(ByVal request As autoCompleteRequest) As autoCompleteResponse1
End Interface

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class completeBoard
    
    Private completeBoardRequestField As operSFCREQ
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property CompleteBoardRequest() As operSFCREQ
        Get
            Return Me.completeBoardRequestField
        End Get
        Set
            Me.completeBoardRequestField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(validateMillingREQ)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(startBoardREQ)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(completePCBREQ)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class operSFCREQ
    Inherits genericREQ
    
    Private operationField As String
    
    Private sfcField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property operation() As String
        Get
            Return Me.operationField
        End Get
        Set
            Me.operationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property sfc() As String
        Get
            Return Me.sfcField
        End Get
        Set
            Me.sfcField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(changeResourceStateREQ)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(operSFCREQ)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(validateMillingREQ)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(startBoardREQ)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(completePCBREQ)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class genericREQ
    
    Private softwareRevisionField As String
    
    Private timeStampField As Date
    
    Private resourceIdField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property softwareRevision() As String
        Get
            Return Me.softwareRevisionField
        End Get
        Set
            Me.softwareRevisionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property timeStamp() As Date
        Get
            Return Me.timeStampField
        End Get
        Set
            Me.timeStampField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
    Public Property resourceId() As String
        Get
            Return Me.resourceIdField
        End Get
        Set
            Me.resourceIdField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class autoCompleteResponse
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class autoComplete
    
    Private cfgField As configType
    
    Private serializeSfcResponseListField() As SerializeSfcResponse
    
    Private startBoardRequestField As operSFCREQ
    
    Private sfcField As String
    
    Private siteField As String
    
    Private isMaterialPanelField As Boolean
    
    Private origMsgHashField As Integer
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property cfg() As configType
        Get
            Return Me.cfgField
        End Get
        Set
            Me.cfgField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("serializeSfcResponseList", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property serializeSfcResponseList() As SerializeSfcResponse()
        Get
            Return Me.serializeSfcResponseListField
        End Get
        Set
            Me.serializeSfcResponseListField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
    Public Property startBoardRequest() As operSFCREQ
        Get
            Return Me.startBoardRequestField
        End Get
        Set
            Me.startBoardRequestField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
    Public Property sfc() As String
        Get
            Return Me.sfcField
        End Get
        Set
            Me.sfcField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
    Public Property site() As String
        Get
            Return Me.siteField
        End Get
        Set
            Me.siteField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
    Public Property isMaterialPanel() As Boolean
        Get
            Return Me.isMaterialPanelField
        End Get
        Set
            Me.isMaterialPanelField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
    Public Property origMsgHash() As Integer
        Get
            Return Me.origMsgHashField
        End Get
        Set
            Me.origMsgHashField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class configType
    
    Private entrylistField() As entryType
    
    Private eventlistField() As eventType
    
    Private jobactivitylistField() As activityType
    
    Private eventCfgListField() As eventCfg
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0),  _
     System.Xml.Serialization.XmlArrayItemAttribute("entry", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
    Public Property entrylist() As entryType()
        Get
            Return Me.entrylistField
        End Get
        Set
            Me.entrylistField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1),  _
     System.Xml.Serialization.XmlArrayItemAttribute("event", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
    Public Property eventlist() As eventType()
        Get
            Return Me.eventlistField
        End Get
        Set
            Me.eventlistField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2),  _
     System.Xml.Serialization.XmlArrayItemAttribute("activity", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property jobactivitylist() As activityType()
        Get
            Return Me.jobactivitylistField
        End Get
        Set
            Me.jobactivitylistField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("eventCfgList", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
    Public Property eventCfgList() As eventCfg()
        Get
            Return Me.eventCfgListField
        End Get
        Set
            Me.eventCfgListField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class entryType
    
    Private keyField As String
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property key() As String
        Get
            Return Me.keyField
        End Get
        Set
            Me.keyField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class eventType
    
    Private regexField As String
    
    Private callingservicelistField() As serviceType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property regex() As String
        Get
            Return Me.regexField
        End Get
        Set
            Me.regexField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1),  _
     System.Xml.Serialization.XmlArrayItemAttribute("service", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property callingservicelist() As serviceType()
        Get
            Return Me.callingservicelistField
        End Get
        Set
            Me.callingservicelistField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class serviceType
    
    Private servicenameField As String
    
    Private paramsField() As entryType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property servicename() As String
        Get
            Return Me.servicenameField
        End Get
        Set
            Me.servicenameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1),  _
     System.Xml.Serialization.XmlArrayItemAttribute("entry", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
    Public Property params() As entryType()
        Get
            Return Me.paramsField
        End Get
        Set
            Me.paramsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class activityType
    
    Private targetstatenameField As String
    
    Private callingservicelistField() As serviceType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property targetstatename() As String
        Get
            Return Me.targetstatenameField
        End Get
        Set
            Me.targetstatenameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1),  _
     System.Xml.Serialization.XmlArrayItemAttribute("service", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property callingservicelist() As serviceType()
        Get
            Return Me.callingservicelistField
        End Get
        Set
            Me.callingservicelistField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class eventCfg
    
    Private descriptionField As String
    
    Private eventIdField As String
    
    Private idEventCfgField As Integer
    
    Private messageIdField As String
    
    Private resourceIdsField As String
    
    Private severityField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property description() As String
        Get
            Return Me.descriptionField
        End Get
        Set
            Me.descriptionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property eventId() As String
        Get
            Return Me.eventIdField
        End Get
        Set
            Me.eventIdField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
    Public Property idEventCfg() As Integer
        Get
            Return Me.idEventCfgField
        End Get
        Set
            Me.idEventCfgField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
    Public Property messageId() As String
        Get
            Return Me.messageIdField
        End Get
        Set
            Me.messageIdField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
    Public Property resourceIds() As String
        Get
            Return Me.resourceIdsField
        End Get
        Set
            Me.resourceIdsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
    Public Property severity() As String
        Get
            Return Me.severityField
        End Get
        Set
            Me.severityField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sap.com/me/production")>  _
Partial Public Class SerializeSfcResponse
    Inherits BasicSplitResponse
End Class

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(SerializeSfcResponse)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sap.com/me/production")>  _
Partial Public Class BasicSplitResponse
    
    Private newSfcRefField As String
    
    Private quantityField As Decimal
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
    Public Property newSfcRef() As String
        Get
            Return Me.newSfcRefField
        End Get
        Set
            Me.newSfcRefField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
    Public Property quantity() As Decimal
        Get
            Return Me.quantityField
        End Get
        Set
            Me.quantityField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class serializeMilling
    
    Private cfgField As configType
    
    Private siteField As String
    
    Private requestField As operSFCREQ
    
    Private sfcField As String
    
    Private origMsgHashField As Integer
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property cfg() As configType
        Get
            Return Me.cfgField
        End Get
        Set
            Me.cfgField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property site() As String
        Get
            Return Me.siteField
        End Get
        Set
            Me.siteField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
    Public Property request() As operSFCREQ
        Get
            Return Me.requestField
        End Get
        Set
            Me.requestField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
    Public Property sfc() As String
        Get
            Return Me.sfcField
        End Get
        Set
            Me.sfcField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
    Public Property origMsgHash() As Integer
        Get
            Return Me.origMsgHashField
        End Get
        Set
            Me.origMsgHashField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class changeResourceStateResponse
    
    Private returnField As genericRSP
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property [return]() As genericRSP
        Get
            Return Me.returnField
        End Get
        Set
            Me.returnField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(validateMillingRSP)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class genericRSP
    
    Private resultCodeField As Integer
    
    Private resultTextField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property resultCode() As Integer
        Get
            Return Me.resultCodeField
        End Get
        Set
            Me.resultCodeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property resultText() As String
        Get
            Return Me.resultTextField
        End Get
        Set
            Me.resultTextField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class validateMillingRSP
    Inherits genericRSP
    
    Private laneField As String
    
    Private processInterlockingField As processInterlocking
    
    Private recipeField As String
    
    Private sfcField As String
    
    Private singleBoardsField() As SingleBoard
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property lane() As String
        Get
            Return Me.laneField
        End Get
        Set
            Me.laneField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property processInterlocking() As processInterlocking
        Get
            Return Me.processInterlockingField
        End Get
        Set
            Me.processInterlockingField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
    Public Property recipe() As String
        Get
            Return Me.recipeField
        End Get
        Set
            Me.recipeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
    Public Property sfc() As String
        Get
            Return Me.sfcField
        End Get
        Set
            Me.sfcField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("singleBoards", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=4)>  _
    Public Property singleBoards() As SingleBoard()
        Get
            Return Me.singleBoardsField
        End Get
        Set
            Me.singleBoardsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class processInterlocking
    
    Private dataSetListField() As processInterlockingDataSet
    
    Private logicalOperatorField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("dataSetList", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
    Public Property dataSetList() As processInterlockingDataSet()
        Get
            Return Me.dataSetListField
        End Get
        Set
            Me.dataSetListField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property logicalOperator() As String
        Get
            Return Me.logicalOperatorField
        End Get
        Set
            Me.logicalOperatorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class processInterlockingDataSet
    
    Private compareModeField As String
    
    Private compareOperationField As String
    
    Private compareTimeValueField As String
    
    Private passFailField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property compareMode() As String
        Get
            Return Me.compareModeField
        End Get
        Set
            Me.compareModeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property compareOperation() As String
        Get
            Return Me.compareOperationField
        End Get
        Set
            Me.compareOperationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
    Public Property compareTimeValue() As String
        Get
            Return Me.compareTimeValueField
        End Get
        Set
            Me.compareTimeValueField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
    Public Property passFail() As String
        Get
            Return Me.passFailField
        End Get
        Set
            Me.passFailField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class SingleBoard
    
    Private locationField As String
    
    Private stateField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property location() As String
        Get
            Return Me.locationField
        End Get
        Set
            Me.locationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property state() As String
        Get
            Return Me.stateField
        End Get
        Set
            Me.stateField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class changeResourceState
    
    Private changeResourceStateRequestField As changeResourceStateREQ
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property changeResourceStateRequest() As changeResourceStateREQ
        Get
            Return Me.changeResourceStateRequestField
        End Get
        Set
            Me.changeResourceStateRequestField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class changeResourceStateREQ
    Inherits genericREQ
    
    Private newStateField As String
    
    Private rcCommentField As String
    
    Private reasonCodeField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property newState() As String
        Get
            Return Me.newStateField
        End Get
        Set
            Me.newStateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property rcComment() As String
        Get
            Return Me.rcCommentField
        End Get
        Set
            Me.rcCommentField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
    Public Property reasonCode() As String
        Get
            Return Me.reasonCodeField
        End Get
        Set
            Me.reasonCodeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class validateMillingResponse
    
    Private returnField As validateMillingRSP
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property [return]() As validateMillingRSP
        Get
            Return Me.returnField
        End Get
        Set
            Me.returnField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class validateMilling
    
    Private validateMillingRequestField As validateMillingREQ
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property validateMillingRequest() As validateMillingREQ
        Get
            Return Me.validateMillingRequestField
        End Get
        Set
            Me.validateMillingRequestField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class validateMillingREQ
    Inherits operSFCREQ
    
    Private amountOfBoardsField As String
    
    Private laneField As String
    
    Private recipeField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property amountOfBoards() As String
        Get
            Return Me.amountOfBoardsField
        End Get
        Set
            Me.amountOfBoardsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property lane() As String
        Get
            Return Me.laneField
        End Get
        Set
            Me.laneField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
    Public Property recipe() As String
        Get
            Return Me.recipeField
        End Get
        Set
            Me.recipeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class startBoardResponse
    
    Private returnField As genericRSP
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property [return]() As genericRSP
        Get
            Return Me.returnField
        End Get
        Set
            Me.returnField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class startBoard
    
    Private startBoardRequestField As startBoardREQ
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property startBoardRequest() As startBoardREQ
        Get
            Return Me.startBoardRequestField
        End Get
        Set
            Me.startBoardRequestField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class startBoardREQ
    Inherits operSFCREQ
    
    Private recipeField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property recipe() As String
        Get
            Return Me.recipeField
        End Get
        Set
            Me.recipeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class completePCBResponse
    
    Private returnField As genericRSP
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property [return]() As genericRSP
        Get
            Return Me.returnField
        End Get
        Set
            Me.returnField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class completePCB
    
    Private completePCBRequestField As completePCBREQ
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property completePCBRequest() As completePCBREQ
        Get
            Return Me.completePCBRequestField
        End Get
        Set
            Me.completePCBRequestField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class completePCBREQ
    Inherits operSFCREQ
    
    Private locationField As String
    
    Private stateField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property location() As String
        Get
            Return Me.locationField
        End Get
        Set
            Me.locationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
    Public Property state() As String
        Get
            Return Me.stateField
        End Get
        Set
            Me.stateField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/")>  _
Partial Public Class completeBoardResponse
    
    Private returnField As genericRSP
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
    Public Property [return]() As genericRSP
        Get
            Return Me.returnField
        End Get
        Set
            Me.returnField = value
        End Set
    End Property
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class completeBoardRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public completeBoard As completeBoard
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal completeBoard As completeBoard)
        MyBase.New
        Me.completeBoard = completeBoard
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class completeBoardResponse1
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public completeBoardResponse As completeBoardResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal completeBoardResponse As completeBoardResponse)
        MyBase.New
        Me.completeBoardResponse = completeBoardResponse
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class completePCBRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public completePCB As completePCB
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal completePCB As completePCB)
        MyBase.New
        Me.completePCB = completePCB
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class completePCBResponse1
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public completePCBResponse As completePCBResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal completePCBResponse As completePCBResponse)
        MyBase.New
        Me.completePCBResponse = completePCBResponse
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class startBoardRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public startBoard As startBoard
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal startBoard As startBoard)
        MyBase.New
        Me.startBoard = startBoard
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class startBoardResponse1
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public startBoardResponse As startBoardResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal startBoardResponse As startBoardResponse)
        MyBase.New
        Me.startBoardResponse = startBoardResponse
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class validateMillingRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public validateMilling As validateMilling
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal validateMilling As validateMilling)
        MyBase.New
        Me.validateMilling = validateMilling
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class validateMillingResponse1
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public validateMillingResponse As validateMillingResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal validateMillingResponse As validateMillingResponse)
        MyBase.New
        Me.validateMillingResponse = validateMillingResponse
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class changeResourceStateRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public changeResourceState As changeResourceState
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal changeResourceState As changeResourceState)
        MyBase.New
        Me.changeResourceState = changeResourceState
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class changeResourceStateResponse1
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public changeResourceStateResponse As changeResourceStateResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal changeResourceStateResponse As changeResourceStateResponse)
        MyBase.New
        Me.changeResourceStateResponse = changeResourceStateResponse
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class serializeMillingRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public serializeMilling As serializeMilling
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal serializeMilling As serializeMilling)
        MyBase.New
        Me.serializeMilling = serializeMilling
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class serializeMillingResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute(Name:="serializeMillingResponse", [Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0),  _
     System.Xml.Serialization.XmlArrayItemAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
    Public serializeMillingResponse1() As SerializeSfcResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal serializeMillingResponse1() As SerializeSfcResponse)
        MyBase.New
        Me.serializeMillingResponse1 = serializeMillingResponse1
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class autoCompleteRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public autoComplete As autoComplete
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal autoComplete As autoComplete)
        MyBase.New
        Me.autoComplete = autoComplete
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class autoCompleteResponse1
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://systemagmbh.com/milling-automation/r1/", Order:=0)>  _
    Public autoCompleteResponse As autoCompleteResponse
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal autoCompleteResponse As autoCompleteResponse)
        MyBase.New
        Me.autoCompleteResponse = autoCompleteResponse
    End Sub
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Public Interface MillingIntegrationServiceR1_5Channel
    Inherits MillingIntegrationServiceR1_5, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Partial Public Class MillingIntegrationServiceR1_5Client
    Inherits System.ServiceModel.ClientBase(Of MillingIntegrationServiceR1_5)
    Implements MillingIntegrationServiceR1_5
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function MillingIntegrationServiceR1_5_completeBoard(ByVal request As completeBoardRequest) As completeBoardResponse1 Implements MillingIntegrationServiceR1_5.completeBoard
        Return MyBase.Channel.completeBoard(request)
    End Function
    
    Public Function completeBoard(ByVal completeBoard1 As completeBoard) As completeBoardResponse
        Dim inValue As completeBoardRequest = New completeBoardRequest()
        inValue.completeBoard = completeBoard1
        Dim retVal As completeBoardResponse1 = CType(Me,MillingIntegrationServiceR1_5).completeBoard(inValue)
        Return retVal.completeBoardResponse
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function MillingIntegrationServiceR1_5_completePCB(ByVal request As completePCBRequest) As completePCBResponse1 Implements MillingIntegrationServiceR1_5.completePCB
        Return MyBase.Channel.completePCB(request)
    End Function
    
    Public Function completePCB(ByVal completePCB1 As completePCB) As completePCBResponse
        Dim inValue As completePCBRequest = New completePCBRequest()
        inValue.completePCB = completePCB1
        Dim retVal As completePCBResponse1 = CType(Me,MillingIntegrationServiceR1_5).completePCB(inValue)
        Return retVal.completePCBResponse
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function MillingIntegrationServiceR1_5_startBoard(ByVal request As startBoardRequest) As startBoardResponse1 Implements MillingIntegrationServiceR1_5.startBoard
        Return MyBase.Channel.startBoard(request)
    End Function
    
    Public Function startBoard(ByVal startBoard1 As startBoard) As startBoardResponse
        Dim inValue As startBoardRequest = New startBoardRequest()
        inValue.startBoard = startBoard1
        Dim retVal As startBoardResponse1 = CType(Me,MillingIntegrationServiceR1_5).startBoard(inValue)
        Return retVal.startBoardResponse
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function MillingIntegrationServiceR1_5_validateMilling(ByVal request As validateMillingRequest) As validateMillingResponse1 Implements MillingIntegrationServiceR1_5.validateMilling
        Return MyBase.Channel.validateMilling(request)
    End Function
    
    Public Function validateMilling(ByVal validateMilling1 As validateMilling) As validateMillingResponse
        Dim inValue As validateMillingRequest = New validateMillingRequest()
        inValue.validateMilling = validateMilling1
        Dim retVal As validateMillingResponse1 = CType(Me,MillingIntegrationServiceR1_5).validateMilling(inValue)
        Return retVal.validateMillingResponse
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function MillingIntegrationServiceR1_5_changeResourceState(ByVal request As changeResourceStateRequest) As changeResourceStateResponse1 Implements MillingIntegrationServiceR1_5.changeResourceState
        Return MyBase.Channel.changeResourceState(request)
    End Function
    
    Public Function changeResourceState(ByVal changeResourceState1 As changeResourceState) As changeResourceStateResponse
        Dim inValue As changeResourceStateRequest = New changeResourceStateRequest()
        inValue.changeResourceState = changeResourceState1
        Dim retVal As changeResourceStateResponse1 = CType(Me,MillingIntegrationServiceR1_5).changeResourceState(inValue)
        Return retVal.changeResourceStateResponse
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function MillingIntegrationServiceR1_5_serializeMilling(ByVal request As serializeMillingRequest) As serializeMillingResponse Implements MillingIntegrationServiceR1_5.serializeMilling
        Return MyBase.Channel.serializeMilling(request)
    End Function
    
    Public Function serializeMilling(ByVal serializeMilling1 As serializeMilling) As SerializeSfcResponse()
        Dim inValue As serializeMillingRequest = New serializeMillingRequest()
        inValue.serializeMilling = serializeMilling1
        Dim retVal As serializeMillingResponse = CType(Me,MillingIntegrationServiceR1_5).serializeMilling(inValue)
        Return retVal.serializeMillingResponse1
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function MillingIntegrationServiceR1_5_autoComplete(ByVal request As autoCompleteRequest) As autoCompleteResponse1 Implements MillingIntegrationServiceR1_5.autoComplete
        Return MyBase.Channel.autoComplete(request)
    End Function
    
    Public Function autoComplete(ByVal autoComplete1 As autoComplete) As autoCompleteResponse
        Dim inValue As autoCompleteRequest = New autoCompleteRequest()
        inValue.autoComplete = autoComplete1
        Dim retVal As autoCompleteResponse1 = CType(Me,MillingIntegrationServiceR1_5).autoComplete(inValue)
        Return retVal.autoCompleteResponse
    End Function
End Class

Namespace systemagmbh.com.millingautomation.r1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema"),  _
     System.Xml.Serialization.XmlRootAttribute(IsNullable:=false)>  _
    Partial Public Class AutomationException
        Inherits Object
        Implements System.Xml.Serialization.IXmlSerializable
        
        Private nodesField() As System.Xml.XmlNode
        
        Private Shared typeName As System.Xml.XmlQualifiedName = New System.Xml.XmlQualifiedName("AutomationException", "http://systemagmbh.com/milling-automation/r1/")
        
        Public Property Nodes() As System.Xml.XmlNode()
            Get
                Return Me.nodesField
            End Get
            Set
                Me.nodesField = value
            End Set
        End Property
        
        Public Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements System.Xml.Serialization.IXmlSerializable.ReadXml
            Me.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader)
        End Sub
        
        Public Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements System.Xml.Serialization.IXmlSerializable.WriteXml
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, Me.Nodes)
        End Sub
        
        Public Function GetSchema() As System.Xml.Schema.XmlSchema Implements System.Xml.Serialization.IXmlSerializable.GetSchema
            Return Nothing
        End Function
        
        Public Shared Function ExportSchema(ByVal schemas As System.Xml.Schema.XmlSchemaSet) As System.Xml.XmlQualifiedName
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName)
            Return typeName
        End Function
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema"),  _
     System.Xml.Serialization.XmlRootAttribute(IsNullable:=false)>  _
    Partial Public Class ECoBaseMeClient61Exception
        Inherits Object
        Implements System.Xml.Serialization.IXmlSerializable
        
        Private nodesField() As System.Xml.XmlNode
        
        Private Shared typeName As System.Xml.XmlQualifiedName = New System.Xml.XmlQualifiedName("ECoBaseMeClient61Exception", "http://systemagmbh.com/milling-automation/r1/")
        
        Public Property Nodes() As System.Xml.XmlNode()
            Get
                Return Me.nodesField
            End Get
            Set
                Me.nodesField = value
            End Set
        End Property
        
        Public Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements System.Xml.Serialization.IXmlSerializable.ReadXml
            Me.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader)
        End Sub
        
        Public Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements System.Xml.Serialization.IXmlSerializable.WriteXml
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, Me.Nodes)
        End Sub
        
        Public Function GetSchema() As System.Xml.Schema.XmlSchema Implements System.Xml.Serialization.IXmlSerializable.GetSchema
            Return Nothing
        End Function
        
        Public Shared Function ExportSchema(ByVal schemas As System.Xml.Schema.XmlSchemaSet) As System.Xml.XmlQualifiedName
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName)
            Return typeName
        End Function
    End Class
End Namespace
