Namespace Alarm

    ''' <summary>
    ''' Defines different types of alarms
    ''' </summary>
    Public Enum PredefinedAlarmTypes

        ''' <summary>
        ''' The alarm is generated by an emergency stop
        ''' </summary>
        EmergencyStop

        ''' <summary>
        ''' The alarm is generated by a safety indication
        ''' </summary>
        Safety

        ''' <summary>
        ''' The alarm is generated by a security door
        ''' </summary>
        Door

        ''' <summary>
        ''' The alarm is generated by a light curtain
        ''' </summary>
        LightCurtain

    End Enum

End Namespace